#
# Module manifest for module 'pwsh-srt'
#
# Generated by: Bjarke Lindberg
#
# Generated on: 10-04-2021
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'pwsh-srt.psm1'

    # Version number of this module.
    ModuleVersion     = '0.0.1'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID              = '261e3e6c-b381-44b4-985e-d8e388cf6199'

    # Author of this module
    Author            = 'Bjarke Lindberg'

    # Company or vendor of this module
    CompanyName       = 'Beverli.NET'

    # Copyright statement for this module
    Copyright         = '(c) Bjarke Lindberg. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Contains cmdlets for manipulating subtitle files (.srt)'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @( 
        'ConvertFrom-Srt',
        'ConvertTo-Srt', 
        'Add-SrtTimeDifference'
        )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @(
    )

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()

    # List of all files packaged with this module
    # FileList          = @('pwsh-srt.psm1')

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('Subtitle', 'srt')

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            ProjectUri = 'https://git.beverli.net/bvli/pwsh-srt'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

